# Created with package:mono_repo v2.3.0
language: dart

jobs:
  include:
    - stage: analyze
      name: "SDK: dev; PKG: petitparser; TASKS: `dartanalyzer --enable-experiment=non-nullable --fatal-warnings --fatal-infos .`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: dev; PKG: petitparser; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_1
    - stage: analyze
      name: "SDK: dev; PKG: petitparser_examples; TASKS: `dartanalyzer --enable-experiment=non-nullable --fatal-warnings --fatal-infos .`"
      dart: dev
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_0
    - stage: analyze
      name: "SDK: dev; PKG: petitparser_examples; TASKS: `dartfmt --dry-run --set-exit-if-changed .`"
      dart: dev
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_1
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser; TASKS: `pub run --enable-experiment=non-nullable test --platform vm`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_2
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser; TASKS: `pub run --enable-experiment=non-nullable test --platform chrome`"
      dart: dev
      os: linux
      env: PKGS="petitparser"
      script: ./tool/travis.sh command_3
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser_examples; TASKS: `pub run --enable-experiment=non-nullable test --platform vm`"
      dart: dev
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_2
    - stage: unit_test
      name: "SDK: dev; PKG: petitparser_examples; TASKS: `pub run --enable-experiment=non-nullable test --platform chrome`"
      dart: dev
      os: linux
      env: PKGS="petitparser_examples"
      script: ./tool/travis.sh command_3

stages:
  - analyze
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - petitparser/.dart_tool/build
    - petitparser_examples/.dart_tool/build
